name: Code quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v1
        with:
          version: latest

      - name: Import Sorting
        run: biome check --apply-unsafe .

      - name: Format Code
        run: biome format --write .

      - name: Lint Code
        run: biome lint .

      - name: Run Biome
        run: biome ci .
